# Generated by Django 3.2 on 2021-05-14 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0004_auto_20210514_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='registermodel',
            name='is_expert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registermodel',
            name='is_industry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registermodel',
            name='is_institute',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registermodel',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
    ]
