# Generated by Django 3.2 on 2021-05-15 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0005_auto_20210515_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registermodel',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='registermodel',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
    ]
