# Generated by Django 3.2 on 2021-05-15 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0006_auto_20210515_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='qualification',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
