# Generated by Django 3.2 on 2021-05-19 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0008_expert'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='experience',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
