# Generated by Django 3.2 on 2021-05-22 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0009_expert_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registermodel',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
