# Generated by Django 3.2 on 2021-05-23 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0012_institute_mobile_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
