# Generated by Django 3.2 on 2021-05-26 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0013_institute_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=255)),
                ('job_requirements', models.CharField(max_length=500)),
                ('job_description', models.TextField()),
                ('stipend', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(max_length=100)),
                ('contact_mail', models.EmailField(blank=True, max_length=254, null=True)),
                ('duration', models.CharField(blank=True, max_length=20, null=True)),
                ('date_of_posting', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
