# Generated by Django 3.2 on 2021-05-27 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0014_jobmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmodel',
            name='contact_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
