# Generated by Django 3.2 on 2021-05-27 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0015_jobmodel_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodel',
            name='enrolled_students',
            field=models.ManyToManyField(related_name='course', to='web_app.Student'),
        ),
    ]
