# Generated by Django 3.2 on 2021-05-28 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0017_industry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Industry',
        ),
    ]
