# Generated by Django 3.2 on 2021-05-31 09:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0019_industry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodel',
            name='enrolled_students',
            field=models.ManyToManyField(related_name='course', to=settings.AUTH_USER_MODEL),
        ),
    ]
