# Generated by Django 3.2 on 2021-06-03 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0020_alter_coursemodel_enrolled_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerAwareness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=500)),
                ('banner_image', models.ImageField(upload_to='career/')),
            ],
        ),
    ]
